### ISSUE TITLE
Segfault on this map

### ISSUE THREAD

**Issue by fsandel** [fsandel/cub3D#36]
No idea why, but this map segfaults

NO textures/wood.png
SO textures/colorstone.png
WE textures/graywallshade1.png
EA textures/graywallshade2.png

F 54,69,79
C 04,02,73

        1111111111111111111111111
        1000000000110000000000001
        1011000001110000000000001
        1001000000000000000000001
111111111011000001110000000000001
1000000000110000011101111DD111111
11110111111111011100000000001
11110111111111011101010010001
11000000110101011110000010001
10000000000000000D00000010001
1000000000000000111101001DD01
11000001110101011111011110N0111
11110111 1110101 101111010001
11111111 1111111 111111111111

**Comment by fsandel** [comment]
seems like it correlates with door in display

**Comment by fsandel** [comment]
if there is no door texture but a door in the map, there is no error, but it segfaults if door is shown but there is no door texture in map file

**Comment by philippschwarzmueller** [comment]
@fsandel can you still reproduce this? cause i can't and this ticket is also quite old
