### ISSUE TITLE
sprites being drawn where you shouldnt be able to see them

### ISSUE THREAD

**Issue by philippschwarzmueller** [fsandel/cub3D#50]
<img width="1112" alt="Screen Shot 2023-05-03 at 6 08 28 PM" src="https://user-images.githubusercontent.com/51891575/235975205-392fd6d4-54c8-4979-90c0-dbb092646192.png">
this happens if you very carefully approach a corner, so that the center of the sprite is probably still hit by the rays, but then draws over the cube where it shouldnt - any ideas @fsandel ?

**Comment by fsandel** [comment]
Works as intended, player has x-ray vision

**Comment by fsandel** [comment]
Fix is already in pipeline, happens since there is only one ray cast to the enemy to save resources 
Next version of enemies will have multiple rays to check for collision
Eta beginning next week

**Comment by fsandel** [comment]
significantly improved on main
